[package]
name = "chnots-tauri"
version = "0.0.120"
description = "Chnots"
authors = [ "org.codeberg.wangzh",]
license = ""
repository = ""
edition = "2021"
rust-version = "1.88.0"

[lib]
name = "app_lib"
crate-type = [ "staticlib", "cdylib", "rlib",]

[dependencies]
tauri-plugin-log = "2"
tauri-plugin-fs = "2"
tauri-plugin-http = "2"
tauri-plugin-opener = "2"

[dependencies.serde_json]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.log]
workspace = true

[dependencies.tauri]
version = "2"
features = [ "devtools",]

[dependencies.chnots-core]
path = "../../lib/backend"
default-features = false
features = [ "tauri",]

[build-dependencies.tauri-build]
version = "2.3.0"
features = []
