[mapper]
type = "sqlite"
filepath = "./transient/sqlite/chnots.db"

[server]
port = 3012
tls_key = "./transient/tls.key"
tls_cert = "./transient/tls.crt"

[file_backup]
backup_dir = "./transient/sqlite-backup"
period = 1800


[attachment]
base_dir = "./transient/sqlite-asset"
