[mapper]
type = "postgres"
user = "chnotsdev"
pass = "chnotsdev"
dbname = "chnotsdev"
host = "localhost"
port =  5432


[server]
port = 3012
tls_key = "./transient/tls.key"
tls_cert = "./transient/tls.crt"

[file_backup]
backup_dir = "./transient/pg-backup"
period = 1800


[attachment]
base_dir = "./transient/pg-attachments"
