[mapper]
type = "sqlite"
filepath = "/home/chin/chnots.db"

[server]
port = 3014
tls_key = "/home/chin/files/private/tls-keys/tls.key"
tls_cert = "/home/chin/files/private/tls-keys/tls.crt"

[file_backup]
backup_dir = "/home/chin/chnots-dev/backup"
period = 1800


[attachment]
base_dir = "/home/chin/chnots-dev/attachments"
