#!/usr/bin/env bash


CSDIR="$(dirname "$(realpath "$0")")"
PROJECT_DIR="$(git rev-parse --show-toplevel)"

echo "=> Project Dir: $PROJECT_DIR"

try_bump_version() {
    local ver
    cat "$(git rev-parse --git-path COMMIT_EDITMSG)" | grep -v "^#"
    ver="$(cat "$(git rev-parse --git-path COMMIT_EDITMSG)" | grep -v "^#" | grep -Eo 'bump to v?[0-9]*\.[0-9]*\.[0-9]*' | sed 's/bump to //g' | head -1)"

    if [ -n "$ver" ]; then
        echo "-> Bump version(pre-hook): $ver"
        "$PROJECT_DIR/tools/bump-version" --set-version "$ver"
    fi
}

"$PROJECT_DIR/tools/format-all" 
try_bump_version

echo "=> $CSDIR/git-pre-commit Finished"
