#!/usr/bin/env bash

PROJECT_DIR="$(git rev-parse --show-toplevel)"

echo "-> Format code"
cd "$PROJECT_DIR"


files=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

[ -z "$files" ] && exit 0

# Prettify all selected files
cd "$PROJECT_DIR/web" && pnpm lint

echo "$files" | grep ".rs$" | xargs rustfmt --edition 2024 

# Add back the modified/prettified files to staging
echo "$files" | xargs git add

echo "-> Format code finished"
