#!/usr/bin/env bash

PROJECT_DIR="$(git rev-parse --show-toplevel)"

cargo_fmt() {
    echo "-> Cargo format"
    cd "$PROJECT_DIR"
    cargo fmt
}

prettier_fmt() {
    local files

    echo "-> Frontend format"
    cd "$PROJECT_DIR"
    if [ ! -f  "$PROJECT_DIR/web/node_modules/.bin/prettier" ]; then
        return
    fi

    files=$(git diff --cached --name-only --diff-filter=ACMR | grep -v "rs$" | sed 's| |\\ |g')
    
    [ -z "$files" ] && return 0

    # Prettify all selected files

    echo "$files" | xargs "$PROJECT_DIR/web/node_modules/.bin/prettier" --ignore-unknown --write

    # Add back the modified/prettified files to staging
    echo "$files" | xargs git add
}
cargo_fmt
prettier_fmt

echo "-> Formating Finished"