#!/usr/bin/env bash

PROJECT_DIR="$(git rev-parse --show-toplevel)"

echo "-> Format code"
cd "$PROJECT_DIR"


files=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

[ -z "$files" ] && exit 0

# Prettify all selected files
if [ -f  "$PROJECT_DIR/web/node_modules/.bin/prettier" ]; then
    echo "$files" | grep -v ".rs$" | xargs "$PROJECT_DIR/web/node_modules/.bin/prettier" --ignore-unknown --write
fi
echo "$files" | grep ".rs$" | xargs rustfmt 

# Add back the modified/prettified files to staging
echo "$files" | xargs git add

echo "-> Format code finished"
