#!/usr/bin/env bash

set -euo pipefail

CSDIR="$(dirname "$(realpath "$0")")"
PROJECT_DIR="$(git rev-parse --show-toplevel)"

VER="$1"
if ! echo "$VER" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' ; then
    echo "Version is invalid, please input a valid semver version(x.y.z)"
    exit 1
fi

cd "$PROJECT_DIR"

"$CSDIR/_impl/bump-version" --set-version "$VER"

cargo check

git add .
git commit -m "ver: bump to $VER"
git tag "v$VER"
