#!/usr/bin/env python3

import re
import typing
import os
import os.path as path

WORK_DIR = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
print("=> workdir:", WORK_DIR)
os.chdir(WORK_DIR)

TYPE_MAP = {
    "DateTime<FixedOffset>": "Date",
    "FieldData<Bytes>": "Blob",
    "bool": "boolean",
    "String": "string",
    "i64": "number",
    "i32": "number",
    "isize": "number",
    "usize": "number",
    "Text": "DbText",
    "SharedStr": "string",
    "u16": "number",
    "RecordState": "object",
    "HashMap": "Record",
}


class RustStruct:
    struct_name: str
    fields: typing.Dict[str, str]  # field_name, field_type

    def __init__(self, struct_name: str = "", fields: typing.Dict[str, str] = None):
        self.struct_name = struct_name
        self.fields = fields if fields is not None else {}

    def __repr__(self):
        fields_str = (
            "{" + ", ".join([f"'{k}': '{v}'" for k, v in self.fields.items()]) + "}"
        )
        return f"RustStruct(struct_name='{self.struct_name}', fields={fields_str})"


def parse_rust_struct_block(struct_block_code: str) -> RustStruct:
    lines = struct_block_code.splitlines()
    rust_struct = RustStruct()
    in_struct = False

    struct_decl_pattern = re.compile(
        r"pub(?:\(crate\))?\s+struct\s+([a-zA-Z_0-9<>,:]+)\s*{?"
    )

    field_name_pattern = re.compile(
        r"pub(?:\(crate\))?\s+(\w+):\s*([a-zA-Z0-9_:<>, ]+),?"
    )

    for line in lines:
        line = line.strip()

        if not in_struct:
            struct_match = struct_decl_pattern.match(line)
            if struct_match:
                rust_struct.struct_name = struct_match.group(1)
                in_struct = True
                continue
        else:
            if line == "}":
                if rust_struct.struct_name:
                    return rust_struct
                else:
                    return None

            if line.startswith("#["):
                continue

            field_match = field_name_pattern.match(line)
            if field_match:
                field_name = field_match.group(1)
                field_type = field_match.group(2)
                rust_struct.fields[field_name] = field_type
            elif line.startswith("pub"):
                parts = re.split(r":\s*", line, 1)
                if len(parts) == 2:
                    name_part = parts[0]
                    type_part = parts[1].strip()

                    name_match = re.search(r"pub(?:\(crate\))?\s+(\w+)", name_part)
                    if name_match:
                        field_name = name_match.group(1)
                        if type_part.endswith(","):
                            field_type = type_part[:-1].strip()
                        else:
                            field_type = type_part.strip()
                        rust_struct.fields[field_name] = field_type

    return rust_struct


def parse_rust_file_structs(file_path: str) -> typing.List[RustStruct]:
    if not os.path.exists(file_path):
        print(f"{file_path} is absent")
        return []

    rmod = (
        file_path.replace("lib/backend/src/", "").replace(".rs", "").replace("/", "::")
    )
    import subprocess

    content = subprocess.check_output(
        ["cargo", "expand", rmod],
        cwd=WORK_DIR + "/lib/backend",
        encoding="utf8",
        stderr=subprocess.DEVNULL,
    )
    lines = content.split("\n")

    parsed_structs = []

    struct_blocks = []
    in_struct_block = False
    brace_level = 0
    current_struct_lines = []

    for line_num, line in enumerate(lines):
        stripped_line = line.strip()
        print("line", stripped_line)

        if not in_struct_block and re.match(
            r"pub(?:\(crate\))?\s+struct\s+[a-zA-Z_0-9<>,:]+\s*{?", stripped_line
        ):
            in_struct_block = True
            brace_level = 0
            current_struct_lines = []

        if in_struct_block:
            current_struct_lines.append(line)
            brace_level += stripped_line.count("{")
            brace_level -= stripped_line.count("}")

            if brace_level == 0 and "}" in stripped_line:
                print(" => extract: \n    ", "\n    ".join(current_struct_lines))
                struct_blocks.append("\n".join(current_struct_lines))
                in_struct_block = False
                current_struct_lines = []

    for block in struct_blocks:
        parsed_struct = parse_rust_struct_block(block)
        if parsed_struct and parsed_struct.struct_name:
            parsed_structs.append(parsed_struct)

    return parsed_structs


def get_type_position(code: str, type_name: str):
    type_patterns = [
        re.compile(r"export type\s+([\w<,>]+)\s*=\s*{([^}]+)};?", re.DOTALL),
        re.compile(r"export type\s+([\w<,>]+)\s*=\s*object;?"),
    ]

    for type_pattern in type_patterns:
        matches = list(type_pattern.finditer(code))

        for match in matches:
            name = match.group(1)

            if name == type_name:
                start_pos = match.start(0)
                end_pos = match.end(0)
                return start_pos, end_pos

    return None


def get_ts_type(rust_type: str):
    rust_type = rust_type.strip()
    outer = None
    inner = None

    if rust_type in TYPE_MAP:
        return TYPE_MAP[rust_type]

    def mapt(rt):
        return TYPE_MAP[rt] if rt in TYPE_MAP else rt

    if (
        (left_a := rust_type.find("<")) >= 0
        and ((comma := rust_type.find(",")) <= 0 or left_a < comma)
        and rust_type.endswith(">")
    ):
        start = left_a
        outer = rust_type[:start]
        inner = rust_type[start + 1 : -1]
    else:
        inner = rust_type

    if outer == "Option":
        return get_ts_type(inner) + "| undefined"
    elif outer == "Vec" or outer == "HashSet":
        return get_ts_type(inner) + "[]"
    else:
        if "(" in inner:
            raise Exception(f"unsupported type {inner}")
        if outer is not None:
            return f"{mapt(outer)}<{get_ts_type(inner)}>"

        if "," in inner:
            segs = inner.split(",")
            return ", ".join([get_ts_type(x) for x in segs])

        return mapt(inner)


def convert_rs_2_ts(rtype: RustStruct):
    fields = "object"

    def type_wrapper(v):
        mid = get_ts_type(v.strip().rstrip(","))
        undef = mid.endswith("| undefined")
        return ":" + mid if not undef else "?:" + mid.replace("| undefined", "")

    if len(rtype.fields) > 0:
        fields = (
            "{\n"
            + "\n".join([f"  {k}{type_wrapper(v)};" for (k, v) in rtype.fields.items()])
            + "\n}"
        )

    return f"""export type {rtype.struct_name} = {fields}; """


def sync_one_file(serverfile: str):
    webfile = serverfile.replace("lib/backend/src", "web/src").replace(".rs", ".ts")

    print("=> work on:", serverfile, webfile)
    if not path.exists(webfile):
        raise Exception(f"file {webfile} is absent")

    rtypes = parse_rust_file_structs(serverfile)
    with open(webfile) as f:
        web_content = f.read()
    for rt in rtypes:
        print(" => parse struct:", rt.struct_name)
        if rt.struct_name.endswith("<"):
            print(" -> skip: ", rt.struct_name)
            continue

        pos = get_type_position(web_content, rt.struct_name)
        web_new = convert_rs_2_ts(rt)
        print(" -> parsed: \n    ", web_new.replace("\n", "\n    "))
        if pos is not None:
            web_content = web_content[0 : pos[0]] + web_new + web_content[pos[1] :]
        else:
            web_content = web_content + "\n" + web_new

    with open(webfile, "w") as f:
        f.write(web_content)


def work_and_do():
    for root, dirs, files in os.walk("lib/backend/src", topdown=False):
        for name in files:
            fullpath = os.path.join(root, name)
            if "sync/dto" in fullpath:
                continue
            if name == "dto.rs" or name == "po.rs":
                sync_one_file(fullpath)


work_and_do()
