@startuml ccc
participant c [
    Chnot
    ----
    id
    meta_id
    tree_id
    content
    omit_tid
    insert_time
]

participant h [
    Chnot Hierarchy
    ----
    id
    chnot_id
    prev_chnot_id
    parent_chnot_id
    insert_time
]

participant n [
    Nested Chnot Header
    ----
    id
    category
    ""title""
    namespace
    pinned
    omit_tid
    insert_time
    update_time
]

-> n: 覆盖



@enduml