@startuml
participant Instance1 as i1
participant Instance2 as i2

i1 -> i1: getNodeList
i1 -> i2: {id, version}
i2 -> i2: check version
alt version is not matched
    i2 -> i1: stop syncing
else
    i2 -> i1: send last sync time
end

i1 -> i1: check last sync time is the same value
alt same time
    i1 -> i2: send data
else
    i1->: fail
end

i1 -> i2: send {otid, omit_tid, tid} list and table_name
i2 -> i2: calc more, less and\n the same items.

i2 -> i1: not samed
i1 -> i2: send message

@enduml