name: 'publish'

on: [push]

# This workflow will trigger on each push to the `release` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: 'ubuntu-latest' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Set env on push
        if: github.event_name == 'push'
        run: |
          echo "INPUT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          # echo "INPUT_TAG=$(git tag --points-at HEAD)" >> $GITHUB_ENV
          echo "INPUT_TAG=v0.0.1" >> $GITHUB_ENV

      - name: Set env on trigger
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "INPUT_SHA=${{ github.event.inputs.sha }}" >> $GITHUB_ENV
          echo "INPUT_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
    
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Java
        if: matrix.platform == 'ubuntu-latest' # This must match the platform 
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: '17'

      - name: Setup Android SDK
        if: matrix.platform == 'ubuntu-latest' # This must match the platform 
        uses: android-actions/setup-android@v3

      - name: Install NDK
        if: matrix.platform == 'ubuntu-latest' # This must match the platform 
        run: sdkmanager "ndk;29.0.13599879"

      - name: install Rust stable(linux)
        if: matrix.platform == 'ubuntu-latest' # This must match the platform 
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android, x86_64-linux-android, x86_64-unknown-linux-gnu
          
      - name: install Rust stable(windows)
        if: matrix.platform == 'windows-latest' # This must match the platform 
        uses: dtolnay/rust-toolchain@stable

      - name: install ubuntu dependencies
        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: initialize 
        run: |
          make init
          mkdir ./release

      - name: build web
        run: make build-web

      - name: build-server
        run: |
          make build-server 
          mv target/release/chnots-server ./release/chnot-server-0.0.1
        
      # - name: tauri build
      #   run: make build-tauri-desktop 
      # - name: setup Android signing
      #   if: matrix.platform == 'ubuntu-latest' # This must match the platform 
      #   run: |
      #     cd ./tauri/src-tauri/gen/android
      #     echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > key.properties
      #     echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> key.properties
      #     echo "storePassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> key.properties
      #     base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
      #     echo "storeFile=$RUNNER_TEMP/keystore.jks" >> key.properties
      #     echo "key.properties created."
      #     cd ../../../.. # Go back to root

      # - name: Build tauri android
      #   if: matrix.platform == 'ubuntu-latest' # This must match the platform 
      #   run: make build-tauri-android
      #   env:
      #     NDK_HOME: /usr/local/lib/android/sdk/ndk/29.0.13599879
      # - uses: actions/upload-artifact@v4
      #   if: matrix.platform == 'ubuntu-latest' # This must match the platform
      #   with:
      #     name: chnot.apk
      #     path: tauri/src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk

      - name: Upload scheduler binary
        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/*
